spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URI:jdbc:mysql://localhost:3306/clienthealth}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 50

gemfire:
  manager:
    port: 1098
  locator:
    host-port: localhost[10334]
  log:
    level: config
  server:
    name: DefaultGemfireServer
  pdx:
    disk-store-dir: /home/derrickwong/workspaces/
  async-event:
    batch-size: 200
    batch-time-interval: 5000
    max-queue-memory: 500
    dispatcher-thread: 10
  cache:
    server:
      bind-address: 0.0.0.0
      hostname-for-clients: ${CACHE_SERVER_HOSTNAME:localhost}